### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StephanStS**

### CODE REVIEW

**Comment by eschava** [comment]
Sorry, but I'm not an approved committer for this node
I've created this branch for the pull request to the main branch but it hasn't been approved yet

**Comment by StephanStS** [comment]
Changes were submitted to original upstream branch.

**Comment by StephanStS** [comment]
@eschava: BTW, do you know [this node](https://flows.nodered.org/node/node-red-contrib-persist)? You did a pull request in 2017 to this node.

**Comment by eschava** [comment]
@StephanStS No, I don't. I did a pull request to json-db-node-red node

**Pull request closed without merging**
